@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Software Defined Infrastructure" #lightblue {

    interface "Software Defined Infrastructure" as i {
            /sdi/getresources()
            /sdi/releaseresources()
            /sdi/sdi/getresources()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "Cloud" {
                 string name
                 string ename
                    }
                    Cloud *--> "n" Resource : resources
                            Cloud o--> "n" Device : devices
                            Cloud o--> "n" AggregatedDevice : adevices
                            Cloud o--> "n" DataCenter : datacenters
                            Cloud *--> "n" Reservation : reservations
                            Cloud *--> "n" Request : requests
            

    class "Request" {
                 string name
                 string ename
                 string type
                             confirm()
            }
                    Request *--> "n" Attribute : requirements
                            Request *--> "n" Reservation : reservations
                            Request o--> "1" Cloud : cloud
                            Request o--> "1" LandscapeRequest : parent
            

    class "Reservation" {
                 number cost
                             confirm()
                     free()
            }
                    Reservation o--> "1" Device : device
                            Reservation o--> "1" Request : request
                            Reservation o--> "1" Cloud : cloud
            

    class "Resource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                    }
                    Resource *--> "n" Attribute : capabilities
                            Resource *--> "n" Attribute : available
                            Resource *--> "n" Attribute : metrics
                            Resource o--> "n" Hardware : hardware
                            Resource o--> "n" ServiceInstance : instances
                            Resource o--> "1" Cloud : cloud
            




}
User --> i
"Software Defined Infrastructure" --> Used

@enduml
