@startuml

left to right direction
Actor "IT Ops" as ITOps


rectangle "Software Defined Infrastructure" #lightblue {
usecase "Manage Resources" as ManageResources
    ITOps --> ManageResources
    }

@enduml
