version: "3.7"
services:
  frontend:
    image: madajaju/pingtest
    networks:
      - sibling
      - parent

networks:
  sibling:
    driver: overlay
  parent:
    external:
      name: ${APPNAME}_sdi_family
