@startuml

actor "Data Engineer" as DataEngineer

actor "Data Scientist" as DataScientist

actor "Chief Data Officer" as ChiefDataOfficer




DataEngineer -> "Data Definition Framework": Manage Data Pipeline
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info

DataEngineer -> "Data Definition Framework": Manage Data Blue Prints
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info

DataEngineer -> "Data Definition Framework": Manage Data Procedures
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info

DataScientist -> "Data Definition Framework": Manage Data Blue Prints
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info

DataScientist -> "Data Definition Framework": Manage Meta Data
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info

ChiefDataOfficer -> "Data Definition Framework": Manage Data Procedures
"Data Definition Framework" -> bin: /edgemere/info
bin -> REST: /edgemere/info


@enduml
