@startuml


Actor "Chief Data Officer" as ChiefDataOfficer


rectangle "Data Definition Framework" as DDF  #lightblue {
        usecase "Manage Data Procedures" as ManageDataProcedures
    ChiefDataOfficer --> ManageDataProcedures

}

rectangle "Data Management Layer" as DML  #lightblue {
        usecase "Manage Data Governance" as ManageDataGovernance
    ChiefDataOfficer --> ManageDataGovernance
    usecase "Manage Data Policies" as ManageDataPolicies
    ChiefDataOfficer --> ManageDataPolicies
    usecase "Manage Data Strategy" as ManageDataStrategy
    ChiefDataOfficer --> ManageDataStrategy

}


@enduml
