@startuml


Actor "Data Scientist" as DataScientist


rectangle "Common Data Services" as CDS  #lightblue {
        usecase "Manage Data" as ManageData
    DataScientist --> ManageData

}

rectangle "Data Definition Framework" as DDF  #lightblue {
        usecase "Manage Data Blue Prints" as ManageDataBluePrints
    DataScientist --> ManageDataBluePrints
    usecase "Manage Meta Data" as ManageMetaData
    DataScientist --> ManageMetaData

}


@enduml
