version: "3.7"
services:
  frontend:
    image: alpine
    command: ping parent
    networks:
      parent:
        aliases:
          - cpl_do
          - do

networks:
  sibling:
    driver: overlay
  parent:
    external:
      name: ${APPNAME}_cpl_family
