@startuml

<%
let pkgs = {};
for(let i in package.depends) {
    let dpkg = package.depends[i];
    pkgs[dpkg.shortname] = {name: dpkg.name, color:dpkg.color, classes:{}};
}
for(let cname in package.classes) {
    let cls = package.classes[cname].definition;
    for(let aname in cls.associations) {
        let assoc = cls.associations[aname];
        let atype = assoc.type;
        let aclass = global.classes[atype];
        if(aclass) {
            let pkg = aclass.definition.package;
            if(!pkgs.hasOwnProperty(pkg.shortname)) {
                pkgs[pkg.shortname] = {name: pkg.name, color: pkg.color, classes:{}};
            }
            pkgs[pkg.shortname].classes[atype] = 1;
        }
    }
}
for(let pname in pkgs) {
    let pkg = pkgs[pname];
%>
package "<%= pkg.name %>" #<%= pkg.color.replace('#', '') %> {
    <% for(let cname in pkg.classes) { %>
        class <%= cname %> {
        }
    <% } -%>
}
<% } %>

package "<%= package.name %>" #<%= package.color.replace('#', '') %> {

    interface "<%= package.name %>" as i {
    <% for (let iname in package.interface) {
        let inter = package.interface[iname];
    -%>
        <%= iname %>()
    <% } %>
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "<%= package.name %>" #<%= package.color.replace('#','') %> {
    <% for(let cname in package.classes) {
        let cls = package.classes[cname].definition;
    -%>
    class "<%= cname %>" {
        <% for(let aname in cls.attributes) {
           let attr = cls.attributes[aname];
         -%>
         <%= attr.type %> <%= aname %>
        <% } -%>
        <% for(let mname in cls.methods) { -%>
             <%= mname %>()
        <% } -%>
    }
    <% for(let aname in cls.associations) {
        let assoc = cls.associations[aname];
        -%>
        <% if(assoc.owner) { -%>
    <%= cname %> *--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
        <% } else { -%>
    <%= cname %> o--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
        <% } -%>
    <% } %>
    <% if(cls.extends) { %>
        <%= cls.extends %> <|-- <%= cname %>
    <% } %>
<% } %>
}

<% for(let i in package.depends) {
    let dpkg = package.depends[i];
    %>
    "<%= package.name %>" --> "<%= dpkg.name %>"
<% } %>

@enduml
