version: "3.7"
services:
  top:
    image: ailtire_service:swarm
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - '3000:3000'
    deploy:
      replicas: 2
    environment:
    - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
    - AILTIRE_TASK={{.Task.Name}}-{{.Task.Slot}}
    - AILTIRE_APPNAME=${AILTIRE_APPNAME}
    networks:
    - children
networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}__family
