version: "3.7"
services:
  frontend:
    image: cpl_web
    networks:
      - parent
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.cpl.loadbalancer.server.port=3000
        - traefik.http.routers.cpl.rule=PathPrefix(`/cpl`)
        - traefik.http.routers.cpl_http.service=cpl
        - traefik.http.routers.cpl_http.entrypoints=http
  gw:
    image: containous/whoami
    networks:
      parent:
        aliases:
          - cpl
      children:
        aliases:
          - parent
      sibling:
        aliases:
          - gateway
networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_cpl_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${APPNAME}_family
