@startuml


usecase "Manage Stuff" as ManageStuff

Actor "Actor" as Actor

Actor --> ManageStuff



usecase "DosomethinagAgain" as DosomethinagAgain #lightgrey

ManageStuff --> DosomethinagAgain

usecase "DosomethinagElse" as DosomethinagElse #lightgrey

ManageStuff --> DosomethinagElse

usecase "Dosomething" as Dosomething #lightgrey

ManageStuff --> Dosomething

@enduml
