@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Data Management Layer" #lightblue {

    interface "Data Management Layer" as i {
            /diml/dml/data/govern()
            /diml/dml/data/policies()
            /diml/dml/data/sources()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "Data" {
                 string access
                    }
                    Data o--> "1" DataSource : source
                            Data o--> "n" DataInstance : instances
            

    class "DataAdaptor" {
                 string name
                    }
                    DataAdaptor o--> "n" DataBluePrint : blueprint
            

    class "DataBluePrint" {
                 string name
                    }
                    DataBluePrint *--> "n" DataAdaptor : adaptors
                            DataBluePrint *--> "n" DataFlow : flows
            

    class "DataInstance" {
                 string name
                    }
                    DataInstance o--> "1" Data : data
                            DataInstance o--> "1" DataReference : reference
                            DataInstance o--> "1" ServiceInstance : service
                            DataInstance o--> "n" SourceMetaData : source
                            DataInstance o--> "n" MetaData : metadata
                            DataInstance o--> "n" LineageMetaData : lineage
            

    class "DataReference" {
                 string name
                 string connection
                             load()
            }
                    DataReference o--> "n" DataInstance : instances
            

    class "DataSource" {
                 string name
                 string type
                    }
                    DataSource o--> "1" Resource : resource
                            DataSource *--> "n" Data : data
            

    class "LineageMetaData" {
                 string creationAction
                    }
                    LineageMetaData o--> "n" DataInstance : parents
            

    class "MetaData" {
                 string name
                 string value
                    }
                    MetaData o--> "1" DataInstance : metadata
            

    class "SourceMetaData" {
                 string connection
                    }
                    SourceMetaData *--> "range" model : name
            




}
User --> i
"Data Management Layer" --> Used

@enduml
