@startuml

actor "Chief Data Officer" as ChiefDataOfficer

actor "Data Engineer" as DataEngineer




ChiefDataOfficer -> "Data Management Layer": Manage Data Governance
"Data Management Layer" -> bin: data/govern
bin -> REST: data/govern

ChiefDataOfficer -> "Data Management Layer": Manage Data Policies
"Data Management Layer" -> bin: data/policies
bin -> REST: data/policies

ChiefDataOfficer -> "Data Management Layer": Manage Data Strategy
"Data Management Layer" -> bin: /edgemere/info
bin -> REST: /edgemere/info

DataEngineer -> "Data Management Layer": Manage Data Sources
"Data Management Layer" -> bin: data/sources
bin -> REST: data/sources


@enduml
