version: "3.7"
services:
  frontend:
    image: sdi_sdc_web
    networks:
      - sibling
      - parent
      - top
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.sdi_sdc.loadbalancer.server.port=3000
        - traefik.http.routers.sdi_sdc_http.rule=PathPrefix(`/sdi/sdc`)
        - traefik.http.routers.sdi_sdc_http.service=sdi_sdc
        - traefik.http.routers.sdi_sdc_http.entrypoints=http
  gw:
    image: sdi_sdc_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_sdi_sdc_family
  sibling:
    driver: overlay
  parent:
    external:
      name: ${APPNAME}_sdi_family
  top:
    external:
      name: ${APPNAME}_family
