@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Common Data Services" #lightblue {

    interface "Common Data Services" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


}
User --> i
"Common Data Services" --> Used

@enduml
