@startuml


usecase "Manage Data" as ManageData

Actor "Data Scientist" as DataScientist

DataScientist --> ManageData

Actor "Data Analyst" as DataAnalyst

DataAnalyst --> ManageData

Actor "Data Engineer" as DataEngineer

DataEngineer --> ManageData



usecase "Absorb-Data" as Absorb-Data #lightgrey

ManageData --> Absorb-Data

usecase "Destroy-Data" as Destroy-Data #lightgrey

ManageData --> Destroy-Data

usecase "Egress-Data" as Egress-Data #lightgrey

ManageData --> Egress-Data

usecase "Move-Data" as Move-Data #lightgrey

ManageData --> Move-Data

@enduml
