@startuml

left to right direction


queue external #black [
    <b><color:white>external</color></b>
]
    
interface 80
80 -- external
    
interface 443
443 -- external
    
interface 8080
8080 -- external
    
boundary children #black


stack "examplestacks" as examplestacksStack {
    queue examplestacksStack #blue [
        <b><color:white>parent</color></b>
    ]
}
stack "examplestacks_t" as examplestacks_tStack {
    queue examplestacks_tStack #blue [
        <b><color:white>parent</color></b>
    ]
}
stack "examplestacks_t2" as examplestacks_t2Stack {
    queue examplestacks_t2Stack #blue [
        <b><color:white>parent</color></b>
    ]
}



stack  "examplestacks" #lightgreen {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    childrennet -[#black]- children
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    siblingnet -[#blue]- sibling


node "frontend" as frontendService {
    card "/web" as webmap
    card "/docs" as docsmap
    
}
node "admin" as adminService
node "top" as topService
node "top2" as top2Service
node "pubsub" as pubsubService
node "web" as webService
node "doc" as docService

        collections "examplestacks:latest" as examplestackslatestimage
            collections "examplestacks_t:latest" as examplestacks_tlatestimage
            collections "examplestacks_t2:latest" as examplestacks_t2latestimage
    
        artifact "redis" as redisimage
    
        artifact "traefik:latest" as traefiklatestimage
    
        artifact "examplestacks_web" as examplestacks_webimage
    
        artifact "examplestacks_doc" as examplestacks_docimage
    
}

external -[#black]- frontendService

webmap -[#blue]-> webService

docsmap -[#blue]-> docService

adminService -[#black]- childrennet

topService -[#black]- childrennet

top2Service -[#black]- childrennet

pubsubService -[#black]- childrennet

pubsubService -[#blue]- siblingnet

webService -[#blue]- siblingnet

webService -[#black]- childrennet

docService -[#blue]- siblingnet

docService -[#black]- childrennet
adminService .... examplestackslatestimage
topService .... examplestacks_tlatestimage
top2Service .... examplestacks_t2latestimage
pubsubService .... redisimage
webService .... examplestacks_webimage
docService .... examplestacks_docimage

frontendService .... traefiklatestimage

examplestackslatestimage --> examplestacksStack

examplestacks_tlatestimage --> examplestacks_tStack

examplestacks_t2latestimage --> examplestacks_t2Stack


@enduml
