#!/bin/sh

DOCKER=docker
CONTEXT=$AILTIRE_CONTEXT
NAME=$AILTIRE_TAG
env

case $CONTEXT in
<% for(let name in contexts) {
%>
<%= name -%>)
    COMPOSE_FILE=<%= contexts[name].file %>
    APP_NAME=$NAME-<%= contexts[name].tag %>
    ;;
<% } -%>
esac

case $ACTION in
    install)
        echo "Deploying Stack"
        $DOCKER stack deploy --compose-file $COMPOSE_FILE $APP_NAME
        ;;
    uninstall)
        echo "Removing Stack"
        $DOCKER stack rm $APP_NAME
        ;;
    upgrade)
        echo "Upgrading stack"
        $DOCKER stack deploy --compose-file $COMPOSE_FILE $APP_NAME
        ;;
    status)
        $DOCKER stack ps $APP_NAME
        ;;
    *)
        echo "Deploying Stack"
        $DOCKER stack deploy --compose-file $COMPOSE_FILE $APP_NAME
        ;;
esac

echo "Action $ACTION complete for $NAME"

