@startuml


usecase "Manage Resources" as ManageResources

Actor "IT Ops" as ITOps

ITOps --> ManageResources



usecase "GetRsources" as GetRsources #lightgrey

ManageResources --> GetRsources

usecase "ListResources" as ListResources #lightgrey

ManageResources --> ListResources

usecase "ReleaseRsources" as ReleaseRsources #lightgrey

ManageResources --> ReleaseRsources

@enduml
