version: "3.7"
services:
  frontend:
    image: sdi_sdn_web
    networks:
      - sibling
  gw:
    image: sdi_sdn_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_sdi_sdn_family
  sibling:
    driver: overlay
  parent:
    external:
      name: ${APPNAME}_sdi_family
