@startuml

class Scenario {
    name : string
    description: string
    method: string
}
class Parameter {
    name : string
    description : string
    required: boolean
    type: enum[string,boolean,number,ref]
}
class Actor {
}
class Step {
    action: string
    parameters: Map
}

Scenario o-> Actor : actors
Scenario "0" *--> "n" Step : steps
Scenario *--> "n" Parameter : inputs

@enduml
