@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Command Physical Layer" #lightgray {

    interface "Command Physical Layer" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


}
User --> i
"Command Physical Layer" --> Used

@enduml
