version: "3.7"
services:
  frontend:
    image: t_s_web
    networks:
      - sibling
  gw:
    image: t_s_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_STACKNAME}_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_PARENT}_family
