@startuml


Actor "IT Ops" as ITOps


rectangle "Software Defined Infrastructure" as SDI  #lightblue {
        usecase "Manage Resources" as ManageResources
    ITOps --> ManageResources

}


@enduml
