@startuml
<% let ucNoSpace = usecase.name.replace(/ /g, '') %>

usecase "<%= usecase.name %>" as <%= ucNoSpace %> #yellow
<% for(let aname in usecase.actors) {
aname = aname.replace(/\s/g, '');
let actor = actors[aname];
%>
Actor "<%= actor.name %>" as <%= aname %>

<%= aname %> --> <%= ucNoSpace %>
<% } %>

<% for(let sname in usecase.scenarios) {
let snameNoSpace = sname.replace(/ /g, '')
%>
usecase "<%= sname %>" as <%= snameNoSpace %> #lightgrey

<%= ucNoSpace %> --> <%= snameNoSpace %>
<% } %>

<% for(let sname in usecase.extends) {
let snameNoSpace = sname.replace(/ /g, '')
%>
usecase "<%= sname %>" as <%= snameNoSpace %> #lightyellow

<%= ucNoSpace %> <-- <%= snameNoSpace %> : extends
<% } %>

<% for(let sname in usecase.extended) {
let snameNoSpace = sname.replace(/ /g, '')
%>
usecase "<%= sname %>" as <%= snameNoSpace %> #lightyellow

<%= ucNoSpace %> --> <%= snameNoSpace %> : extends
<% } %>

<% for(let sname in usecase.includes) {
let snameNoSpace = sname.replace(/ /g, '')
%>
usecase "<%= sname %>" as <%= snameNoSpace %> #white

<%= ucNoSpace %> ..> <%= snameNoSpace %> : includes
<% } %>

<% for(let sname in usecase.included) {
let snameNoSpace = sname.replace(/ /g, '')
%>
usecase "<%= sname %>" as <%= snameNoSpace %> #white

<%= ucNoSpace %> <.. <%= snameNoSpace %> : includes
<% } %>
@enduml
