@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Service Management Layer" #lightblue {

    interface "Service Management Layer" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


}
User --> i
"Service Management Layer" --> Used

@enduml
