@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Security Aspect" #lightblue {

    interface "Security Aspect" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


}
User --> i
"Security Aspect" --> Used

@enduml
