@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Software Defined Infrastructure" #lightyellow {

    interface "Software Defined Infrastructure" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


}
User --> i
"Software Defined Infrastructure" --> Used

@enduml
