@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Distributed Information Management Layer" #lightblue {

    interface "Distributed Information Management Layer" as i {
            /diml/dump()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
    


package CDS {
}

package DDF {
}

package DML {
}

}
User --> i
"Distributed Information Management Layer" --> Used

@enduml
