@startuml

class "Resource" as Model {
 string name
 string ename
 boolean disabled
 string type

 
}

rectangle "Attribute" as Attribute {
}

Model *--> "n" Attribute : capabilities


rectangle "Attribute" as Attribute {
}

Model *--> "n" Attribute : available


rectangle "Attribute" as Attribute {
}

Model *--> "n" Attribute : metrics


rectangle "Hardware" as Hardware {
}

Model o--> "n" Hardware : hardware


rectangle "ServiceInstance" as ServiceInstance {
}

Model o--> "n" ServiceInstance : instances


rectangle "Cloud" as Cloud {
}

Model o--> "1" Cloud : cloud




@enduml
