@startuml
<% for(let aname in actors) { %>
actor "<%= aname %>"
<% } %>

entity EventBus

box <%= package.name %> <%= package.color %>
    boundary <%= package.shortname %> #white
    participant DataModel #white
end box

<% for(let aname in actors) {
%>
"<%= aname %>" -> <%= package.shortname %>: <%= scenario.name %>
<%= package.shortname %> -> <%= package.shortname %>: <%= scenario.method %>
<% } %>
DataModel --/ EventBus : Model.Event

<% for(let i in package.depends) {
    let  dpkg = package.depends[i];
    if(dpkg) {
-%>
box "<%= dpkg.name %>" <%= dpkg.color %>
    boundary <%= dpkg.shortname %> #white
end box
EventBus -\ <%= dpkg.shortname %>: method()
<%= dpkg.shortname %> --/ EventBus: Model.Event2
<% }
} %>
EventBus --/ <%= package.shortname %> : method2()
@enduml
