@startuml

class "Data" as Model {
 string access

 
}

rectangle "DataSource" as DataSource {
}

Model o--> "1" DataSource : source


rectangle "DataInstance" as DataInstance {
}

Model o--> "n" DataInstance : instances




@enduml
