@startuml

class "DataBluePrint" as Model {
 string name

 
}

rectangle "DataAdaptor" as DataAdaptor {
}

Model *--> "n" DataAdaptor : adaptors


rectangle "DataFlow" as DataFlow {
}

Model *--> "n" DataFlow : flows




@enduml
