@startuml

class "LineageMetaData" as Model {
 string creationAction
 string name
 string value

 
}

rectangle "DataInstance" as DataInstance {
}

Model o--> "n" DataInstance : parents


rectangle "DataInstance" as DataInstance {
}

Model o--> "1" DataInstance : metadata




@enduml
