@startuml



package "exampleUseCase" #lightgreen {

    interface "exampleUseCase" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "exampleUseCase" #lightgreen {


rectangle "Top Package" #white {
}

rectangle "Top Stuff" #white {
}

}



@enduml
