@startuml



package "Top Stuff" lightblue {

    interface "Top Stuff" as i {
            /exampleusecase/ts/data/govern()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Top Stuff" lightblue {
    
}



@enduml
