@startuml



package "Top Package" #lightblue {

    interface "Top Package" as i {
            /exampleusecase/tp/data/govern()
            /exampleusecase/tp/data/source/name()

    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Top Package" #lightblue {


}



@enduml
