@startuml

left to right direction


queue external #black [
    <b><color:white>external</color></b>
]

interface 80
80 -- external

interface 443
443 -- external

interface 8080
8080 -- external



entity ailtire_appname_family #black

rectangle "mypackage" as mypackageStack #lightblue {
    queue mypackageStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}



package "myapp" #lavender {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]

    childrennet -[#black]- ailtire_appname_family

    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]

    node "frontend" as frontendService {
        card "/web" as webmap
        card "/docs" as docsmap
        card "mypackage" as mypackagemap

    }
    node "admin" as adminService
    node "mypackage" as mypackageService
    node "pubsub" as pubsubService
    node "web" as webService
    node "doc" as docService

    collections "myapp:latest" as myapplatestimage
    collections "myapp_mypackage:latest" as mypackagelatestimage
    artifact "redis" as redisimage
    artifact "traefik:latest" as traefiklatestimage
    artifact "myapp_web" as myapp_webimage
    artifact "myapp_doc" as myapp_docimage

}

external -[#black]- frontendService
webmap -[#black]-> webService
docsmap -[#black]-> docService
adminService -[#black]- childrennet
mypackageService -[#black]- childrennet
pubsubService -[#black]- childrennet
pubsubService -[#blue]- siblingnet
webService -[#blue]- siblingnet
webService -[#black]- childrennet
docService -[#blue]- siblingnet
docService -[#black]- childrennet
adminService .... myapplatestimage
mypackageService .... mypackagelatestimage
pubsubService .... redisimage
webService .... myapp_webimage
docService .... myapp_docimage
frontendService .... traefiklatestimage

mypackagelatestimage --> mypackageStack
mypackageStacksnet --[#black]-- ailtire_appname_family

@enduml
