version: "3.7"
services:
  frontend:
    image: sdi_sds_web
    networks:
      - parent
      - top
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.sdi_sds.loadbalancer.server.port=3000
        - traefik.http.routers.sdi_sds_http.rule=PathPrefixStrip(`/sdi/sds`)
        - traefik.http.routers.sdi_sds_http.service=sdi_sds
        - traefik.http.routers.sdi_sds_http.entrypoints=http
  gw:
    image: sdi_sds_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_sdi_sds_family
  sibling:
    driver: overlay
  parent:
    external:
      name: ${APPNAME}_sdi_family
  top:
    external:
      name: ${APPNAME}_family
