version: "3.7"
services:
  frontend:
    image: madajaju/pingtest
    networks:
      children:
        aliases:
          - parent
      sibling:
        aliases:
          - sdi
      parent:
        aliases:
          - sdi
  gw:
    image: madajaju/pingtest
    networks:
      children:
        aliases:
          - parentgw
      sibling:
        aliases:
          - sdigw
      parent:
        aliases:
          - sdigw

networks:
  sibling:
    driver: overlay
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_sdi_family
  parent:
    external:
      name: ${APPNAME}_family
