name: Docker Services Publish
on:
  release:
    types: [created]
jobs:
  build_swarm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test location
      run: ls -latr src/Services/swarm
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src/Services/swarm
        file: ./src/Services/swarm/deploy/Dockerfile
        tags: madajaju/ailtire_service:swarm
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_doc
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./src/Services/builddoc
          file: ./src/Services/builddoc/Dockerfile
          tags: madajaju/ailtire_builddoc
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
