@startuml

left to right direction

Actor "Actor" as Actor



rectangle "Top Package" as tp  lightblue {
        usecase "Manage Stuff" as ManageStuff
    
        Actor ---> ManageStuff
        

}

rectangle "Top Stuff" as ts  lightblue {
        usecase "More Stuff" as MoreStuff
    
        Actor --> MoreStuff
        
    usecase "More Stuff2" as MoreStuff2
    
        Actor --> MoreStuff2
        
    usecase "More Stuff3" as MoreStuff3
    
        Actor --> MoreStuff3
        
    usecase "More Stuff4" as MoreStuff4
    
        Actor --> MoreStuff4
        
    usecase "More Stuff6" as MoreStuff6
    
        Actor --> MoreStuff6
        
    usecase "More Stuff7" as MoreStuff7
    
        Actor --> MoreStuff7
        
    usecase "More Stuff8" as MoreStuff8
    
        Actor --> MoreStuff8
        

}


@enduml
